<?php
require __DIR__ . '/../vendor/autoload.php';
use Dompdf\Dompdf;
include __DIR__ . '/../config.php';


// Ambil filter dari GET
$statusFilter = $_GET['status_filter'] ?? '';
$tglFilter    = $_GET['tgl_filter'] ?? '';

$where = [];
if($statusFilter) $where[] = "status='$statusFilter'";
if($tglFilter)    $where[] = "tgl_booking='$tglFilter'";
$whereSql = count($where) > 0 ? "WHERE ".implode(' AND ', $where) : "";

$q = mysqli_query($koneksi, "SELECT * FROM booking $whereSql ORDER BY id DESC");

$dompdf = new Dompdf();

$html = '<h2 style="text-align:center;">Laporan Booking Kinasih Cafe & Space</h2>';
$html .= '<p style="text-align:center;">'.($statusFilter ? "Status: $statusFilter" : "Semua Status").' | '.($tglFilter ? "Tanggal: $tglFilter" : "Semua Tanggal").'</p>';
$html .= '<hr>';

$html .= '<table border="1" cellpadding="4" cellspacing="0" width="100%">
<tr style="background:#ddd;">
    <th>ID Booking</th>
    <th>Nama</th>
    <th>No HP</th>
    <th>Alamat</th>
    <th>Tgl Booking</th>
    <th>Jam Datang</th>
    <th>Jenis</th>
    <th>Jumlah Kursi</th>
    <th>Status</th>
</tr>';

while($b = mysqli_fetch_assoc($q)){
    $html .= '<tr>
        <td>'.$b['id_booking'].'</td>
        <td>'.$b['nama'].'</td>
        <td>'.$b['nohp'].'</td>
        <td>'.$b['alamat'].'</td>
        <td>'.$b['tgl_booking'].'</td>
        <td>'.$b['jam_datang'].'</td>
        <td>'.$b['jenis_booking'].'</td>
        <td>'.$b['jumlah_kursi'].'</td>
        <td>'.$b['status'].'</td>
    </tr>';
}

$html .= '</table>';

// Footer
$html .= '<hr><p style="text-align:center; font-size:10px;">Generated by Kinasih Cafe Reservation System</p>';

$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'landscape');
$dompdf->render();

// Nama file PDF
$filename = "laporan_booking_".date('Ymd').".pdf";

$dompdf->stream($filename, ["Attachment" => false]);
?>
